export const pricingCatalog = {
  valorMinimo: 2800,
  ticketMedioRecente: 5500,
  condicoesPagamento: {
    aVista: '10% de desconto',
    parcelado: 'Em até 10x no cartão',
  },
  tabelaReferencia: [
    { item: 'Valor mínimo', valor: 'R$ 2.800' },
    { item: 'Ticket médio recente', valor: '~ R$ 5.500' },
    { item: 'Antebraço interno (1 projeto)', valor: 'a partir de R$ 2.800' },
    { item: 'Ombro ao punho externo (2 projetos)', valor: 'a partir de R$ 5.500' },
  ],
  tempoAtendimento: {
    inicio: 'Todos os atendimentos iniciam às 10h da manhã',
    disponibilidade: 'O artista tira o dia todo para o seu projeto, então venha com tempo totalmente disponível.',
    umProjeto: 'O tempo médio de atendimento para 1 projeto (antebraço interno, antebraço externo, braço externo ou braço interno) é de 6 a 8 hs totais contando apresentação, pausas durante a tatuagem e pausa para o almoço.',
    doisProjetos: 'O tempo médio de atendimento para 2 projetos (fechamento de braço externo ou fechamento interno) é de 10hs totais contando apresentação, pausas durante a tatuagem e pausa para o almoço.',
    quatroProjetos: 'O tempo médio de atendimento para 4 projetos (fechamento completo de braço) serão dois dias de atendimento.',
    parcelamento: 'Atenção: todos os trabalhos podem ser parcelados em até 10x.',
  },
  porRegiao: {
    'Antebraço Interno': 2800,
    'Antebraço Externo': 3000,
    'Braço Externo': 3800,
    'Fechamento de Braço Externo (ombro ao punho)': 5500,
    'Fechamento Interno de Braço': 5500,
    'Fechamento Total de Braço': 10800,
    'Canela': 3000,
    'Panturrilha': 3000,
    'Coxa Frontal': 4500,
    'Coxa Posterior': 4000,
    'Fechamento de Perna Frontal': 6800,
    'Fechamento de Perna Posterior': 6500,
    'Fechamento de Costas Parcial Superior': 8800,
    'Fechamento de 1/2 Costas - Central': 6000,
    'Fechamento de 1/2 Costas': 6800,
    'Fechamento de Costas Completo': 11800,
    'Braço Interno': 3800,
    'Fechamento Total de Perna': null,
    'Costas Total': null,
    'Costas Parcial': null,
    'Peitoral Total': null,
    'Meio Peitoral': null,
    'Abdômen': null,
  } as Record<string, number | null>,
  observacoes: 'Valores para execução em Atibaia-SP. Todos os trabalhos podem ser parcelados em até 10x.',
};

export const investmentBands = [
  'R$ 2.800 a R$ 4.500',
  'R$ 4.500 a R$ 6.500',
  'R$ 6.500 a R$ 8.500',
  'Acima de R$ 8.500',
];

export const bodyAreas = [
  'Antebraço Externo',
  'Antebraço Interno',
  'Braço Externo',
  'Braço Interno',
  'Fechamento Total de Braço',
  'Fechamento de Braço Externo',
  'Fechamento de Braço Interno',
  'Fechamento de Perna Frontal',
  'Fechamento de Perna Posterior',
  'Fechamento Total de Perna',
  'Costas Total',
  'Costas Parcial',
  'Coxa Frontal',
  'Posterior de Coxa',
  'Panturrilha',
  'Canela',
  'Peitoral Total',
  'Meio Peitoral',
  'Abdômen',
  'Outro',
];
